### ISSUE TITLE
sk login error with Google Auth  

### ISSUE THREAD

**Issue by baditaflorin** [skaffolder/skaffolder-cli#53]
```$sk login  

    _____ _   __      __  __      _     _            __                _____ _      _____   
   / ____| | / /     / _|/ _|    | |   | |           \ \              / ____| |    |_   _|  
  | (___ | |/ / __ _| |_| |_ ___ | | __| | ___ _ __   \ \    ______  | |    | |      | |    
   \___ \| { { / _` |  _|  _/ _ \| |/ _` |/ _ \ '__|   } }  |______| | |    | |      | |    
   ____) | |\ \ (_| | | | || (_) | | (_| |  __/ |     / /            | |____| |____ _| |_   
  |_____/|_| \_\__,_|_| |_| \___/|_|\__,_|\___|_|    /_/              \_____|______|_____|  
                                                                                            


(node:29444) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
The Skaffolder login will open in your default browser...

internal/fs/utils.js:259
    throw err;
    ^

Error: EACCES: permission denied, open '/usr/lib/node_modules/skaffolder-cli/cache/cache/token.json'
    at Object.openSync (fs.js:461:3)
    at Object.writeFileSync (fs.js:1387:35)
    at Object.putSync (/usr/lib/node_modules/skaffolder-cli/node_modules/persistent-cache/index.js:72:16)
    at Socket.<anonymous> (/usr/lib/node_modules/skaffolder-cli/lib/login.js:46:19)
    at Socket.Emitter.emit (/usr/lib/node_modules/skaffolder-cli/node_modules/socket.io-client/node_modules/component-emitter/index.js:133:20)
    at Socket.onevent (/usr/lib/node_modules/skaffolder-cli/node_modules/socket.io-client/lib/socket.js:278:10)
    at Socket.onpacket (/usr/lib/node_modules/skaffolder-cli/node_modules/socket.io-client/lib/socket.js:236:12)
    at Manager.<anonymous> (/usr/lib/node_modules/skaffolder-cli/node_modules/component-bind/index.js:21:15)
    at Manager.Emitter.emit (/usr/lib/node_modules/skaffolder-cli/node_modules/socket.io-client/node_modules/component-emitter/index.js:133:20)
    at Manager.ondecoded (/usr/lib/node_modules/skaffolder-cli/node_modules/socket.io-client/lib/manager.js:345:8)
    at Decoder.<anonymous> (/usr/lib/node_modules/skaffolder-cli/node_modules/component-bind/index.js:21:15)
    at Decoder.Emitter.emit (/usr/lib/node_modules/skaffolder-cli/node_modules/socket.io-parser/node_modules/component-emitter/index.js:133:20)
    at Decoder.add (/usr/lib/node_modules/skaffolder-cli/node_modules/socket.io-parser/index.js:251:12)
    at Manager.ondata (/usr/lib/node_modules/skaffolder-cli/node_modules/socket.io-client/lib/manager.js:335:16)
    at Socket.<anonymous> (/usr/lib/node_modules/skaffolder-cli/node_modules/component-bind/index.js:21:15)
    at Socket.Emitter.emit (/usr/lib/node_modules/skaffolder-cli/node_modules/engine.io-client/node_modules/component-emitter/index.js:133:20) {
  errno: -13,
  syscall: 'open',
  code: 'EACCES',
  path: '/usr/lib/node_modules/skaffolder-cli/cache/cache/token.json'
}
```

**Comment by baditaflorin** [comment]
on the web I just see this 
![image](https://user-images.githubusercontent.com/2330999/81382796-9ea35100-9117-11ea-85bb-6ec4a89e3970.png)

**Comment by baditaflorin** [comment]
If I try to do 
```sudo sk login``` it will never start the browser session
