### ISSUE TITLE
UnhandledPromiseRejectionWarning: Error: Please install pg package manually

### ISSUE THREAD

**Issue by baditaflorin** [skaffolder/skaffolder-cli#56]
```
$ cd first_api_test/server 
$ node --trace-warnings index.js
info: 

-----------------------------------

Starting MyCRM 
Generated by

   _____ _          __  __      _     _           
  / ____| |        / _|/ _|    | |   | |          
 | (___ | | ____ _| |_| |_ ___ | | __| | ___ _ __ 
  \___ \| |/ / _` |  _|  _/ _ \| |/ _` |/ _ \ '__|
  ____) |   < (_| | | | || (_) | | (_| |  __/ |   
 |_____/|_|\_\__,_|_| |_| \___/|_|\__,_|\___|_|   

For more documentation please visit https://skaffolder.com/#/documentation

-----------------------------------


info: Authenticating to the databases...
info: Server started on port 3000
info: Swagger docs at http://localhost:3000/api/docs
(node:21958) UnhandledPromiseRejectionWarning: Error: Please install pg package manually
    at ConnectionManager._loadDialectModule (/home/florin/Desktop/API_design/SKAFFOLDER/first_api_test/server/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:88:15)
    at new ConnectionManager (/home/florin/Desktop/API_design/SKAFFOLDER/first_api_test/server/node_modules/sequelize/lib/dialects/postgres/connection-manager.js:18:24)
    at new PostgresDialect (/home/florin/Desktop/API_design/SKAFFOLDER/first_api_test/server/node_modules/sequelize/lib/dialects/postgres/index.js:14:30)
    at new Sequelize (/home/florin/Desktop/API_design/SKAFFOLDER/first_api_test/server/node_modules/sequelize/lib/sequelize.js:324:20)
    at Database.authenticate (/home/florin/Desktop/API_design/SKAFFOLDER/first_api_test/server/classes/Database_Manage_Film_Example_db.js:74:23)
    at Database.init (/home/florin/Desktop/API_design/SKAFFOLDER/first_api_test/server/classes/Database_Manage_Film_Example_db.js:49:16)
    at Server.init (/home/florin/Desktop/API_design/SKAFFOLDER/first_api_test/server/classes/Server.js:53:35)
    at start (/home/florin/Desktop/API_design/SKAFFOLDER/first_api_test/server/app.js:42:18)
    at Object.<anonymous> (/home/florin/Desktop/API_design/SKAFFOLDER/first_api_test/server/app.js:51:1)
    at Generator.next (<anonymous>)
    at createWarningObject (internal/process/warning.js:152:9)
    at process.emitWarning (internal/process/warning.js:122:15)
    at process.<anonymous> (/home/florin/Desktop/API_design/SKAFFOLDER/first_api_test/server/node_modules/esm/esm.js:1:289642)
    at process.<anonymous> (/home/florin/Desktop/API_design/SKAFFOLDER/first_api_test/server/node_modules/esm/esm.js:1:289518)
    at process.<anonymous> (/home/florin/Desktop/API_design/SKAFFOLDER/first_api_test/server/node_modules/esm/esm.js:1:284879)
    at Object.apply (/home/florin/Desktop/API_design/SKAFFOLDER/first_api_test/server/node_modules/esm/esm.js:1:199341)
    at emitUnhandledRejectionWarning (internal/process/promises.js:149:15)
    at processPromiseRejections (internal/process/promises.js:211:11)
    at processTicksAndRejections (internal/process/task_queues.js:98:32)
(node:21958) Error: Please install pg package manually
    at ConnectionManager._loadDialectModule (/home/florin/Desktop/API_design/SKAFFOLDER/first_api_test/server/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:88:15)
    at new ConnectionManager (/home/florin/Desktop/API_design/SKAFFOLDER/first_api_test/server/node_modules/sequelize/lib/dialects/postgres/connection-manager.js:18:24)
    at new PostgresDialect (/home/florin/Desktop/API_design/SKAFFOLDER/first_api_test/server/node_modules/sequelize/lib/dialects/postgres/index.js:14:30)
    at new Sequelize (/home/florin/Desktop/API_design/SKAFFOLDER/first_api_test/server/node_modules/sequelize/lib/sequelize.js:324:20)
    at Database.authenticate (/home/florin/Desktop/API_design/SKAFFOLDER/first_api_test/server/classes/Database_Manage_Film_Example_db.js:74:23)
    at Database.init (/home/florin/Desktop/API_design/SKAFFOLDER/first_api_test/server/classes/Database_Manage_Film_Example_db.js:49:16)
    at Server.init (/home/florin/Desktop/API_design/SKAFFOLDER/first_api_test/server/classes/Server.js:53:35)
    at start (/home/florin/Desktop/API_design/SKAFFOLDER/first_api_test/server/app.js:42:18)
    at Object.<anonymous> (/home/florin/Desktop/API_design/SKAFFOLDER/first_api_test/server/app.js:51:1)
    at Generator.next (<anonymous>)
    at bl (/home/florin/Desktop/API_design/SKAFFOLDER/first_api_test/server/node_modules/esm/esm.js:1:245412)
    at kl (/home/florin/Desktop/API_design/SKAFFOLDER/first_api_test/server/node_modules/esm/esm.js:1:247659)
    at Object.u (/home/florin/Desktop/API_design/SKAFFOLDER/first_api_test/server/node_modules/esm/esm.js:1:287740)
    at Object.o (/home/florin/Desktop/API_design/SKAFFOLDER/first_api_test/server/node_modules/esm/esm.js:1:287137)
    at Object.<anonymous> (/home/florin/Desktop/API_design/SKAFFOLDER/first_api_test/server/node_modules/esm/esm.js:1:284879)
    at Object.apply (/home/florin/Desktop/API_design/SKAFFOLDER/first_api_test/server/node_modules/esm/esm.js:1:199341)
    at /home/florin/Desktop/API_design/SKAFFOLDER/first_api_test/server/node_modules/esm/esm.js:1:231006
    at /home/florin/Desktop/API_design/SKAFFOLDER/first_api_test/server/node_modules/esm/esm.js:1:231041
    at /home/florin/Desktop/API_design/SKAFFOLDER/first_api_test/server/node_modules/esm/esm.js:1:231254
    at Su (/home/florin/Desktop/API_design/SKAFFOLDER/first_api_test/server/node_modules/esm/esm.js:1:228587)
    at ku (/home/florin/Desktop/API_design/SKAFFOLDER/first_api_test/server/node_modules/esm/esm.js:1:230341)
    at _c (/home/florin/Desktop/API_design/SKAFFOLDER/first_api_test/server/node_modules/esm/esm.js:1:258239)
(node:21958) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
    at createWarningObject (internal/process/warning.js:152:9)
    at process.emitWarning (internal/process/warning.js:122:15)
    at process.<anonymous> (/home/florin/Desktop/API_design/SKAFFOLDER/first_api_test/server/node_modules/esm/esm.js:1:289642)
    at process.<anonymous> (/home/florin/Desktop/API_design/SKAFFOLDER/first_api_test/server/node_modules/esm/esm.js:1:289518)
    at process.<anonymous> (/home/florin/Desktop/API_design/SKAFFOLDER/first_api_test/server/node_modules/esm/esm.js:1:284879)
    at Object.apply (/home/florin/Desktop/API_design/SKAFFOLDER/first_api_test/server/node_modules/esm/esm.js:1:199341)
    at emitDeprecationWarning (internal/process/promises.js:161:11)
    at processPromiseRejections (internal/process/promises.js:213:13)
    at processTicksAndRejections (internal/process/task_queues.js:98:32)
```

**Comment by baditaflorin** [comment]
If I do just npm install it does nt seems to do the trick. 
```
$ cd first_api_test/server
$ npm install                   
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

audited 2509 packages in 3.499s

1 package is looking for funding
  run `npm fund` for details

found 2 moderate severity vulnerabilities
  run `npm audit fix` to fix them, or `npm audit` for details

```

I had to manually do in the /server folder
```
sudo npm install pg
sudo npm install pg           
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

+ pg@8.1.0
added 16 packages from 6 contributors and audited 2526 packages in 3.449s

1 package is looking for funding
  run `npm fund` for details

found 2 moderate severity vulnerabilities
  run `npm audit fix` to fix them, or `npm audit` for details

```
