### ISSUE TITLE
error: SequelizeDatabaseError: column "birthDate" does not exist with default template provided

### ISSUE THREAD

**Issue by baditaflorin** [skaffolder/skaffolder-cli#58]
Steps to reproduce
```
curl -X GET "http://localhost:3000/api/actor/" -H "accept: application/json" -H "Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOjEsIm1haWwiOm51bGwsIm5hbWUiOm51bGwsInN1cm5hbWUiOm51bGwsInVzZXJuYW1lIjoiYWRtaW4iLCJyb2xlcyI6WyJBRE1JTiJdLCJpYXQiOjE1ODg5ODQ2MTcsImV4cCI6MTU4ODk5NTQxN30.YoQ22XEbADYl4dnrRmwTiMaNT5x6nDhKAG1E5lOJBwg"
```
Body response
```
{
  "name": "UNKNOWN",
  "status": 500,
  "message": "Unknown server error"
}
```
Node.js Log
```
/9/2020, 3:48:09 AM GET - /api/actor/ 
error: SequelizeDatabaseError: column "birthDate" does not exist
    at Query.formatError (/home/florin/Desktop/API_design/SKAFFOLDER/first_api_test/server/node_modules/sequelize/lib/dialects/postgres/query.js:366:16)
    at /home/florin/Desktop/API_design/SKAFFOLDER/first_api_test/server/node_modules/sequelize/lib/dialects/postgres/query.js:72:18
    at tryCatcher (/home/florin/Desktop/API_design/SKAFFOLDER/first_api_test/server/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/florin/Desktop/API_design/SKAFFOLDER/first_api_test/server/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/home/florin/Desktop/API_design/SKAFFOLDER/first_api_test/server/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/home/florin/Desktop/API_design/SKAFFOLDER/first_api_test/server/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/home/florin/Desktop/API_design/SKAFFOLDER/first_api_test/server/node_modules/bluebird/js/release/promise.js:725:18)
    at _drainQueueStep (/home/florin/Desktop/API_design/SKAFFOLDER/first_api_test/server/node_modules/bluebird/js/release/async.js:93:12)
    at _drainQueue (/home/florin/Desktop/API_design/SKAFFOLDER/first_api_test/server/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/home/florin/Desktop/API_design/SKAFFOLDER/first_api_test/server/node_modules/bluebird/js/release/async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/home/florin/Desktop/API_design/SKAFFOLDER/first_api_test/server/node_modules/bluebird/js/release/async.js:15:14)
    at processImmediate (internal/timers.js:456:21)
    at process.topLevelDomainCallback (domain.js:137:15)
```
Database SQL script
```
cat schemaDb_Manage_Film_Example_db_postgresql.sql
--
-- Database: manage_film_example_db
--

CREATE DATABASE manage_film_example_db;

-- ENTITIES

--
-- Schema entity actor
--

CREATE TABLE IF NOT EXISTS "actor" (
	birthDate date ,
	name varchar(130)  NOT NULL,
	surname varchar(130) ,
	
	_id SERIAL PRIMARY KEY

);

--
-- Schema entity film
--

CREATE TABLE IF NOT EXISTS "film" (
	genre varchar(130) ,
	title varchar(130)  NOT NULL,
	year numeric ,
	
	_id SERIAL PRIMARY KEY

);

--
-- Schema entity filmmaker
--

CREATE TABLE IF NOT EXISTS "filmmaker" (
	name varchar(130)  NOT NULL,
	surname varchar(130) ,
	
	_id SERIAL PRIMARY KEY

);

--
-- Schema entity user
--

CREATE TABLE IF NOT EXISTS "user" (
	mail varchar(130) ,
	name varchar(130) ,
	password varchar(130)  NOT NULL,
	roles varchar(130) ,
	surname varchar(130) ,
	username varchar(130)  NOT NULL,
	
	_id SERIAL PRIMARY KEY

);


-- Security

ALTER TABLE "user" ALTER COLUMN "password" TYPE varchar(128);

INSERT INTO "user" (username, password, _id) VALUES ('admin', '62f264d7ad826f02a8af714c0a54b197935b717656b80461686d450f7b3abde4c553541515de2052b9af70f710f0cd8a1a2d3f4d60aa72608d71a63a9a93c0f5', 1);

CREATE TABLE IF NOT EXISTS "roles" (
	role varchar(30) ,
	
	-- RELAZIONI

	_user INTEGER  NOT NULL REFERENCES "user"(_id),
	_id SERIAL PRIMARY KEY 

);
INSERT INTO "roles" (role, _user, _id) VALUES ('ADMIN', '1', 1);




-- relation 1:m filmMaker Film - FilmMaker
ALTER TABLE film ADD COLUMN filmMaker INTEGER  NOT NULL REFERENCES "filmmaker"(_id);

-- relation m:m cast Film - Actor
CREATE TABLE IF NOT EXISTS "Film_cast" (
    _id SERIAL PRIMARY KEY,
    id_Film INTEGER  NOT NULL REFERENCES "film"(_id),
    id_Actor INTEGER  NOT NULL REFERENCES "actor"(_id)
```

**Comment by baditaflorin** [comment]
same error when I am trying to access /api/film from http://localhost:3001/actors 
```
/9/2020, 4:57:06 AM GET - /api/film 
error: SequelizeDatabaseError: column "filmMaker" does not exist
    at Query.formatError (/home/florin/Desktop/API_design/SKAFFOLDER/first_api_test/server/node_modules/sequelize/lib/dialects/postgres/query.js:366:16)
    at /home/florin/Desktop/API_design/SKAFFOLDER/first_api_test/server/node_modules/sequelize/lib/dialects/postgres/query.js:72:18
    at tryCatcher (/home/florin/Desktop/API_design/SKAFFOLDER/first_api_test/server/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/florin/Desktop/API_design/SKAFFOLDER/first_api_test/server/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/home/florin/Desktop/API_design/SKAFFOLDER/first_api_test/server/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/home/florin/Desktop/API_design/SKAFFOLDER/first_api_test/server/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/home/florin/Desktop/API_design/SKAFFOLDER/first_api_test/server/node_modules/bluebird/js/release/promise.js:725:18)
    at _drainQueueStep (/home/florin/Desktop/API_design/SKAFFOLDER/first_api_test/server/node_modules/bluebird/js/release/async.js:93:12)
    at _drainQueue (/home/florin/Desktop/API_design/SKAFFOLDER/first_api_test/server/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/home/florin/Desktop/API_design/SKAFFOLDER/first_api_test/server/node_modules/bluebird/js/release/async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/home/florin/Desktop/API_design/SKAFFOLDER/first_api_test/server/node_modules/bluebird/js/release/async.js:15:14)
    at processImmediate (internal/timers.js:456:21)
    at process.topLevelDomainCallback (domain.js:137:15)

```
